DATA_FOLDER = "data"
OUTPUT_FOLDER = "output"

DESCRIPTION_FOLDER = f"{OUTPUT_FOLDER}/descriptions"
ANALYSIS_FOLDER = f"{OUTPUT_FOLDER}/analysis"
GRAPHS_FOLDER = f"{OUTPUT_FOLDER}/graphs"
SUMMARIES_FOLDER = f"{OUTPUT_FOLDER}/summaries"

SAMPLE_ROWS = 5
TOP_UNIQUE_VALUES = 10